export type MenuItem = {
  name: string;
  nameEn: string;
  desc?: string;
  descEn?: string;
  imageUrl: string;
  price: number;
};

export type MenuCategory = {
  id: string;
  label: string;
  labelEn: string;
  items: MenuItem[];
};

const CDN = "https://d3ectyws4rj41r.cloudfront.net/prod_anfascafe";

export const MENU: MenuCategory[] = [
  {
    id: "breakfast",
    label: "الفطور",
    labelEn: "Breakfast",
    items: [
      {
        name: "فطور فالير عربي",
        nameEn: "Arabic Valier Breakfast",
        desc: "مجموعة متنوعة من الفطور مثل: البيض والسلطات الموسمية",
        descEn: "A variety of breakfast items including eggs and seasonal salads",
        imageUrl: `${CDN}/132/8c3a70b2f9a887818085da52052fbc16-(1).jpg`,
        price: 40,
      },
      {
        name: "فطور إنتركونتنتال",
        nameEn: "Intercontinental Breakfast",
        desc: "مجموعة متنوعة من الكروسان المشكل والمربى والزبدة",
        descEn: "Assorted croissants, jam, and butter",
        imageUrl: `${CDN}/132/8c3a70b2f9a887818085da52052fbc16-(1).jpg`,
        price: 40,
      },
      {
        name: "أوملت مكس جبنة",
        nameEn: "Cheese Omelette",
        desc: "بيض مخفوق مع إضافة الجبن",
        descEn: "Scrambled eggs with cheese",
        imageUrl: `${CDN}/132/8c3a70b2f9a887818085da52052fbc16-(1).jpg`,
        price: 25,
      },
      {
        name: "أوملت سادة",
        nameEn: "Plain Omelette",
        desc: "بيض مخفوق بدون إضافات",
        descEn: "Plain scrambled eggs",
        imageUrl: `${CDN}/132/8c3a70b2f9a887818085da52052fbc16-(1).jpg`,
        price: 22,
      },
      {
        name: "سلة كروسان",
        nameEn: "Croissant Basket",
        desc: "مجموعة من قطع الكروسان",
        descEn: "A selection of croissants",
        imageUrl: `${CDN}/144/media-library4YVp3j`,
        price: 22,
      },
    ],
  },
  {
    id: "desserts",
    label: "الحلويات",
    labelEn: "Desserts",
    items: [
      {
        name: "لافا شوكليت",
        nameEn: "Chocolate Lava",
        desc: "كيكة شوكولاته محشية بصوص الكاكاو مع قطعة من الآيس كريم",
        descEn: "Chocolate cake filled with cocoa sauce, served with ice cream",
        imageUrl: `${CDN}/77/media-librarysrfcc9`,
        price: 28,
      },
      {
        name: "شوكليت براونيز",
        nameEn: "Chocolate Brownies",
        desc: "قطع البراونيز المغطى بالشوكولاته مع آيس كريم الفانيليا والفواكه المشكلة",
        descEn: "Brownies topped with chocolate, vanilla ice cream and mixed fruits",
        imageUrl: `${CDN}/109/IMG_4841.jpeg`,
        price: 28,
      },
      {
        name: "بان كيك",
        nameEn: "Pancake",
        desc: "حلى يجمع بين قوام الكريب الهش المغطى بطبقة غنية من الشوكولاتة",
        descEn: "Fluffy pancake topped with rich chocolate",
        imageUrl: `${CDN}/113/e29cf431-69bb-4d7d-8322-c6a218f3c858.jpeg`,
        price: 28,
      },
      {
        name: "وافل",
        nameEn: "Waffle",
        desc: "حلى يُحضّر ويُشوى في قوالب خاصة ليأخذ نقشته المميزة",
        descEn: "Freshly baked waffle with signature patterns",
        imageUrl: `${CDN}/80/media-libraryASwYat`,
        price: 28,
      },
      {
        name: "كريب شوكلاته",
        nameEn: "Chocolate Crepe",
        desc: "حلى يجمع بين قوام الكريب الناعم المغطى بطبقة غنية من الشوكولاتة",
        descEn: "Soft crepe topped with rich chocolate",
        imageUrl: `${CDN}/114/a6161aee-f384-4451-932c-19848b35b786.jpeg`,
        price: 30,
      },
      {
        name: "تشيز كيك نكهات",
        nameEn: "Assorted Cheesecake",
        desc: "طبقة من البسكويت وطبقة من الكريمة اللذيذة",
        descEn: "Biscuit base with creamy topping",
        imageUrl: `${CDN}/110/d67c72c0-77cd-4b67-b37c-c1be12cd9794.jpeg`,
        price: 25,
      },
      {
        name: "كوكيز دبل شوكليت",
        nameEn: "Double Chocolate Cookies",
        desc: "كوكيز غني بنكهة الشوكولاتة المزدوجة",
        descEn: "Cookies rich in double chocolate flavor",
        imageUrl: `${CDN}/82/media-libraryVTBf5D`,
        price: 8,
      },
      {
        name: "بقلاوة مع آيس كريم",
        nameEn: "Baklava with Ice Cream",
        desc: "حلوى شهية من طبقات رقيقة وداخلها مكسرات وآيس كريم",
        descEn: "Delicate layered pastry with nuts, served with ice cream",
        imageUrl: `${CDN}/112/1a934265-94a9-4673-ab57-942973ae65c9.jpeg`,
        price: 28,
      },
    ],
  },
  {
    id: "shisha",
    label: "المعسلات",
    labelEn: "Shisha",
    items: [
      {
        name: "تفاحتين فاخر",
        nameEn: "Premium Two Apples",
        imageUrl: `${CDN}/23/7f2e5a74-16e6-4e66-9b4d-b297d9f28d99.jpeg`,
        price: 45.5,
      },
      {
        name: "تفاحتين مكس",
        nameEn: "Two Apples Mix",
        imageUrl: `${CDN}/24/940065d6-7358-4828-90b1-8e9500fbfd15.jpeg`,
        price: 45.5,
      },
      {
        name: "تفاحتين نخلة",
        nameEn: "Nakhla Two Apples",
        imageUrl: `${CDN}/25/7f2e5a74-16e6-4e66-9b4d-b297d9f28d99.jpeg`,
        price: 45.5,
      },
      {
        name: "عنب توت",
        nameEn: "Grape Berry",
        imageUrl: `${CDN}/26/7f2e5a74-16e6-4e66-9b4d-b297d9f28d99.jpeg`,
        price: 45.5,
      },
      {
        name: "عنب نعناع",
        nameEn: "Grape Mint",
        imageUrl: `${CDN}/27/940065d6-7358-4828-90b1-8e9500fbfd15.jpeg`,
        price: 45.5,
      },
      {
        name: "ليمون نعناع",
        nameEn: "Lemon Mint",
        imageUrl: `${CDN}/28/7f2e5a74-16e6-4e66-9b4d-b297d9f28d99.jpeg`,
        price: 45.5,
      },
      {
        name: "شيشة عدني",
        nameEn: "Adeni Shisha",
        imageUrl: `${CDN}/29/2bb203fe-49f8-44ca-8edf-2828a5569bd3.jpeg`,
        price: 45.5,
      },
    ],
  },
  {
    id: "soft",
    label: "مشروبات غازية",
    labelEn: "Soft Drinks",
    items: [
      {
        name: "ماء",
        nameEn: "Water",
        imageUrl: `${CDN}/45/deb8455d-d232-49c9-a206-1eb8034e263e.jpeg`,
        price: 7,
      },
      {
        name: "مياه غازية",
        nameEn: "Sparkling Water",
        imageUrl: `${CDN}/44/e60d2b8b-99a7-49bc-b2b8-144c25704f2c.jpeg`,
        price: 12,
      },
      {
        name: "بيبسي",
        nameEn: "Pepsi",
        imageUrl: `${CDN}/104/36beac6c-967b-4c0a-a459-79a242c5a9a0.jpeg`,
        price: 10,
      },
      {
        name: "بيبسي دايت",
        nameEn: "Diet Pepsi",
        imageUrl: `${CDN}/74/media-libraryFGr9tH`,
        price: 10,
      },
      {
        name: "سفن آب",
        nameEn: "7 Up",
        imageUrl: `${CDN}/105/1f34246b-7de8-4b3e-8954-af7c34e774dc.jpeg`,
        price: 10,
      },
      {
        name: "سفن آب دايت",
        nameEn: "Diet 7 Up",
        imageUrl: `${CDN}/71/media-librarytok0W9`,
        price: 10,
      },
      {
        name: "موسي سادة",
        nameEn: "Plain Mousse",
        imageUrl: `${CDN}/75/media-libraryRjcqLw`,
        price: 18,
      },
      {
        name: "كود رد",
        nameEn: "Code Red",
        imageUrl: `${CDN}/72/media-librarydhAduM`,
        price: 20,
      },
    ],
  },
  {
    id: "hot",
    label: "المشروبات الساخنة",
    labelEn: "Hot Drinks",
    items: [
      {
        name: "شاي أحمر",
        nameEn: "Black Tea",
        imageUrl: `${CDN}/69/946d747c-aa91-44cf-8be2-1568b7514778.jpeg`,
        price: 8,
      },
      {
        name: "شاي أخضر",
        nameEn: "Green Tea",
        imageUrl: `${CDN}/68/51d6224f-6cbd-4c24-a16f-2affe9b0060f.jpeg`,
        price: 8,
      },
      {
        name: "شاي كرك",
        nameEn: "Karak Tea",
        imageUrl: `${CDN}/70/946d747c-aa91-44cf-8be2-1568b7514778.jpeg`,
        price: 10,
      },
      {
        name: "براد شاي أخضر",
        nameEn: "Green Tea Pot",
        imageUrl: `${CDN}/99/fada2e45-d9d2-4c7c-a10b-52ae97eafbf8.jpeg`,
        price: 25,
      },
      {
        name: "براد شاي مغربي",
        nameEn: "Moroccan Tea Pot",
        imageUrl: `${CDN}/100/fada2e45-d9d2-4c7c-a10b-52ae97eafbf8.jpeg`,
        price: 25,
      },
      {
        name: "براد شاي أحمر",
        nameEn: "Black Tea Pot",
        imageUrl: `${CDN}/15/52a46ba7-aef3-4b21-ba63-c05c745eb21a.jpeg`,
        price: 25,
      },
      {
        name: "قهوة تركي",
        nameEn: "Turkish Coffee",
        imageUrl: `${CDN}/83/7ae61cd1-c708-4d2c-a1ce-dc5ad0a0f705.jpeg`,
        price: 15,
      },
      {
        name: "قهوة تركي حليب",
        nameEn: "Turkish Coffee with Milk",
        imageUrl: `${CDN}/84/7ae61cd1-c708-4d2c-a1ce-dc5ad0a0f705.jpeg`,
        price: 17,
      },
      {
        name: "قهوة اليوم",
        nameEn: "Coffee of the Day",
        imageUrl: `${CDN}/85/9a127905-4715-48c7-bfba-136a4273b400.jpeg`,
        price: 18,
      },
      {
        name: "قهوة أمريكي",
        nameEn: "Americano",
        imageUrl: `${CDN}/89/9a127905-4715-48c7-bfba-136a4273b400.jpeg`,
        price: 18,
      },
      {
        name: "قهوة فرنسي",
        nameEn: "French Coffee",
        imageUrl: `${CDN}/21/a275fd12-4fb1-441a-b67d-519f0d7e5df1.jpeg`,
        price: 18,
      },
      {
        name: "دلة قهوة عربي",
        nameEn: "Arabic Coffee Pot",
        imageUrl: `${CDN}/16/7fedd082-c38d-4349-b122-ad48c0bf08a3.jpeg`,
        price: 28,
      },
      {
        name: "موكا حار",
        nameEn: "Hot Mocha",
        desc: "صوص الشوكولاته الداكنة مع دبل إسبريسو والحليب",
        descEn: "Dark chocolate sauce with double espresso and milk",
        imageUrl: `${CDN}/88/1b7bb212-2c17-4b2c-8418-6f4161dc5c7f.jpeg`,
        price: 18,
      },
      {
        name: "لاتيه حار",
        nameEn: "Hot Latte",
        imageUrl: `${CDN}/86/1b7bb212-2c17-4b2c-8418-6f4161dc5c7f.jpeg`,
        price: 18,
      },
      {
        name: "كابتشينو",
        nameEn: "Cappuccino",
        imageUrl: `${CDN}/92/db8c1d8b-b439-43a7-92ee-c68aee77ed1b.jpeg`,
        price: 18,
      },
      {
        name: "هوت شوكلت",
        nameEn: "Hot Chocolate",
        imageUrl: `${CDN}/93/91dc3e54-b055-4af7-965d-785c4794fb37.jpeg`,
        price: 18,
      },
      {
        name: "كورتادو",
        nameEn: "Cortado",
        imageUrl: `${CDN}/87/1b7bb212-2c17-4b2c-8418-6f4161dc5c7f.jpeg`,
        price: 18,
      },
      {
        name: "فلات وايت",
        nameEn: "Flat White",
        imageUrl: `${CDN}/98/61943bf2-c46d-44a3-af0c-26f06c107b1d.jpeg`,
        price: 18,
      },
      {
        name: "ماتشا لاتيه",
        nameEn: "Matcha Latte",
        desc: "حليب الشوفان مع سيرب وماتشا",
        descEn: "Oat milk with syrup and matcha",
        imageUrl: `${CDN}/90/d440c439-8ac0-47ce-bccb-6ffe93c827c7.jpeg`,
        price: 22,
      },
      {
        name: "سبانش لاتيه حار",
        nameEn: "Hot Spanish Latte",
        desc: "حليب مكثف مع دبل إسبريسو وحليب مسخن",
        descEn: "Condensed milk with double espresso and steamed milk",
        imageUrl: `${CDN}/96/db8c1d8b-b439-43a7-92ee-c68aee77ed1b.jpeg`,
        price: 20,
      },
      {
        name: "إسبريسو سنجل",
        nameEn: "Single Espresso",
        imageUrl: `${CDN}/95/41b645f5-d2e3-49d1-ba02-da3737b36bba.jpeg`,
        price: 15,
      },
      {
        name: "إسبريسو دبل",
        nameEn: "Double Espresso",
        imageUrl: `${CDN}/97/41b645f5-d2e3-49d1-ba02-da3737b36bba.jpeg`,
        price: 17,
      },
      {
        name: "إسبريسو رومانو",
        nameEn: "Espresso Romano",
        desc: "دبل إسبريسو مع عصرة ليمون",
        descEn: "Double espresso with a splash of lemon",
        imageUrl: `${CDN}/46/49d4130f-fe4a-45d9-b7a0-52c6b6606925.jpeg`,
        price: 18,
      },
      {
        name: "إسبريسو بلو بيري",
        nameEn: "Blueberry Espresso",
        desc: "دبل إسبريسو مع التوت الأزرق",
        descEn: "Double espresso with blueberry",
        imageUrl: `${CDN}/91/896048ec-4c2c-4a76-9b94-bb2599fb2ed3.jpeg`,
        price: 18,
      },
      {
        name: "إسبريسو توت أحمر",
        nameEn: "Red Berry Espresso",
        desc: "دبل إسبريسو مع التوت البري الأحمر",
        descEn: "Double espresso with red cranberry",
        imageUrl: `${CDN}/22/ac6ef77f-66aa-4ef4-ab27-a59ac87d19e4.jpeg`,
        price: 18,
      },
      {
        name: "موكاتشينو",
        nameEn: "Mochaccino",
        desc: "شوكولاتة داكنة مع فوم الحليب والحليب والإسبريسو",
        descEn: "Dark chocolate with milk foam, milk, and espresso",
        imageUrl: `${CDN}/20/a275fd12-4fb1-441a-b67d-519f0d7e5df1.jpeg`,
        price: 18,
      },
      {
        name: "كراميل ميكاتو",
        nameEn: "Caramel Macchiato",
        desc: "الإسبريسو مع الكراميل صوص والحليب",
        descEn: "Espresso with caramel sauce and milk",
        imageUrl: `${CDN}/19/542c5b78-7aaf-49d9-8c32-c9bfdc45632b.jpeg`,
        price: 18,
      },
      {
        name: "حار V60",
        nameEn: "Hot V60",
        imageUrl: `${CDN}/106/9edfc85f-2f38-459d-aa23-950b3177153f.jpeg`,
        price: 20,
      },
    ],
  },
  {
    id: "fresh",
    label: "عصائر فريش",
    labelEn: "Fresh Juices",
    items: [
      {
        name: "عصير الفواكه الموسمية",
        nameEn: "Seasonal Fruit Juice",
        desc: "يتكون من الفواكه الموسمية",
        descEn: "Made with seasonal fruits",
        imageUrl: `${CDN}/41/c1a678ac-da14-443b-9d3e-5615e36042b7.jpeg`,
        price: 25,
      },
      {
        name: "عصير ليمون سادة",
        nameEn: "Plain Lemon Juice",
        desc: "خلطة ليمون تمتاز بالحمضية الحلوة والمنعشة",
        descEn: "A refreshing sweet-tangy lemon blend",
        imageUrl: `${CDN}/31/a3e67325-2fae-45ca-8530-38baf04e8f94.jpeg`,
        price: 25,
      },
      {
        name: "عصير ليمون ونعناع",
        nameEn: "Lemon Mint Juice",
        desc: "خلطة ليمون ونعناع تجمع بين حموضة الليمون وانتعاش النعناع",
        descEn: "Lemon and mint combining tanginess and freshness",
        imageUrl: `${CDN}/32/45874118-edb0-4952-8def-20ad7d1a43dd.jpeg`,
        price: 25,
      },
      {
        name: "عصير البطيخ",
        nameEn: "Watermelon Juice",
        desc: "مشروب من لب البطيخ الطازج بنكهته الحلوة وترطيبه العالي",
        descEn: "Fresh watermelon, sweet and hydrating",
        imageUrl: `${CDN}/33/8bbc92f7-f734-4d4d-be0f-46022da8847b.jpeg`,
        price: 25,
      },
      {
        name: "عصير مانجو",
        nameEn: "Mango Juice",
        desc: "قوام كثيف وناعم وطعم فاكهي ورائحة منعشة",
        descEn: "Thick smooth texture with fresh fruity aroma",
        imageUrl: `${CDN}/34/dac6ed70-d6c4-4b2a-b418-2a52d03ba4c5.jpeg`,
        price: 25,
      },
      {
        name: "عصير موز",
        nameEn: "Banana Juice",
        desc: "طعم الموز الحلو الكريمي مع قوام ناعم",
        descEn: "Sweet creamy banana with smooth texture",
        imageUrl: `${CDN}/35/60a235aa-def0-4f2b-8a69-7322622c869f.jpeg`,
        price: 25,
      },
      {
        name: "عصير أفوكادو",
        nameEn: "Avocado Juice",
        desc: "الأفوكادو مع التمر والمكسرات بقوام مخملي",
        descEn: "Avocado with dates and nuts, velvety texture",
        imageUrl: `${CDN}/36/c3aa9d0d-5a7d-487a-8c9a-aea7439fc686.jpeg`,
        price: 25,
      },
      {
        name: "عصير برتقال",
        nameEn: "Orange Juice",
        desc: "مشروب فريش يتميز بحمضية البرتقال الحلوة",
        descEn: "Fresh drink with sweet orange tang",
        imageUrl: `${CDN}/101/b33822bc-e796-4a29-8922-2c810e957bcb.jpeg`,
        price: 25,
      },
      {
        name: "عصير أناناس",
        nameEn: "Pineapple Juice",
        desc: "طعم حلو لاذع بإحساس استوائي منعش",
        descEn: "Sweet tangy tropical refreshment",
        imageUrl: `${CDN}/37/0da79325-c784-4ce3-a0da-df7510318a68.jpeg`,
        price: 25,
      },
      {
        name: "عصير كانتلوب",
        nameEn: "Cantaloupe Juice",
        desc: "نكهة حلوة وقوام ناعم وترطيب عالٍ",
        descEn: "Sweet flavor with smooth hydrating texture",
        imageUrl: `${CDN}/102/f3d40875-f3a3-4bf5-b51d-43438b2c90e3.jpeg`,
        price: 25,
      },
      {
        name: "عصير رمان",
        nameEn: "Pomegranate Juice",
        desc: "لون أحمر جذاب وطعم غني",
        descEn: "Vivid red color with rich taste",
        imageUrl: `${CDN}/38/c1fc8739-20d7-4414-87f7-338a158452bb.jpeg`,
        price: 25,
      },
      {
        name: "عصير فراولة",
        nameEn: "Strawberry Juice",
        desc: "قوام خفيف ومنعش ولون وردي بنكهة فاكهية",
        descEn: "Light refreshing pink fruit juice",
        imageUrl: `${CDN}/103/acca37cd-d72b-43a5-8a1e-8df382a4848f.jpeg`,
        price: 25,
      },
      {
        name: "عصير كوكتيل",
        nameEn: "Cocktail Juice",
        desc: "قوام كثيف غني بالفيتامينات والسكر الطبيعي",
        descEn: "Thick, rich in vitamins and natural sugar",
        imageUrl: `${CDN}/39/11216c00-d39c-4cd9-ab83-6e589e535677.jpeg`,
        price: 25,
      },
    ],
  },
  {
    id: "cold",
    label: "المشروبات الباردة",
    labelEn: "Cold Drinks",
    items: [
      {
        name: "لافوا آيس كوفي",
        nameEn: "Lavoa Iced Coffee",
        desc: "حليب مع قهوة الإسبريسو بنكهة البلوبيري",
        descEn: "Milk with espresso and blueberry flavor",
        imageUrl: `${CDN}/57/IMG_4777.jpeg`,
        price: 25,
      },
      {
        name: "V60",
        nameEn: "V60",
        imageUrl: `${CDN}/12/d4f841b5-8f2c-42e3-aa7a-d353cd161c2e.jpeg`,
        price: 25,
      },
      {
        name: "آيس أمريكانو",
        nameEn: "Iced Americano",
        imageUrl: `${CDN}/58/8ffdbb75-f7c3-4f78-9c52-7fce709acb22.jpeg`,
        price: 23,
      },
      {
        name: "آيس موكا",
        nameEn: "Iced Mocha",
        desc: "صوص الشوكولاتة الداكنة مع الإسبريسو والحليب",
        descEn: "Dark chocolate sauce with espresso and milk",
        imageUrl: `${CDN}/13/4894cc92-b62b-4fff-a40c-0bdc176011c9.jpeg`,
        price: 23,
      },
      {
        name: "آيس شوكلت",
        nameEn: "Iced Chocolate",
        desc: "سموذي الشوكلت مع الحليب",
        descEn: "Chocolate smoothie with milk",
        imageUrl: `${CDN}/14/4894cc92-b62b-4fff-a40c-0bdc176011c9.jpeg`,
        price: 23,
      },
      {
        name: "آيس ماتشا لاتيه",
        nameEn: "Iced Matcha Latte",
        desc: "حليب الشوفان مع سيرب القيقب والماتشا الاحتفالية",
        descEn: "Oat milk with maple syrup and ceremonial matcha",
        imageUrl: `${CDN}/59/718eb9a1-e8c0-45da-87f8-6524eb877bc7.jpeg`,
        price: 25,
      },
      {
        name: "آيس كراميل لاتيه",
        nameEn: "Iced Caramel Latte",
        desc: "الإسبريسو مع صوص الكراميل والحليب",
        descEn: "Espresso with caramel sauce and milk",
        imageUrl: `${CDN}/65/000733ee-fb62-4ade-9110-2ace9468c259.jpeg`,
        price: 23,
      },
      {
        name: "آيس سبانيش لاتيه",
        nameEn: "Iced Spanish Latte",
        desc: "حليب مكثف مع الحليب والإسبريسو",
        descEn: "Condensed milk with milk and espresso",
        imageUrl: `${CDN}/64/ebff1edc-7c61-48fa-8994-340e648f9909.jpeg`,
        price: 25,
      },
      {
        name: "آيس لاتيه",
        nameEn: "Iced Latte",
        desc: "حليب مع الإسبريسو",
        descEn: "Milk with espresso",
        imageUrl: `${CDN}/63/ba6d1353-3049-41cc-a8dd-4e1ccc457f84.jpeg`,
        price: 23,
      },
      {
        name: "آيس وايت موكا",
        nameEn: "Iced White Mocha",
        desc: "صوص الشوكولاتة البيضاء مع الحليب والإسبريسو",
        descEn: "White chocolate sauce with milk and espresso",
        imageUrl: `${CDN}/61/000733ee-fb62-4ade-9110-2ace9468c259.jpeg`,
        price: 23,
      },
      {
        name: "آيس فرابتشينو",
        nameEn: "Iced Frappuccino",
        desc: "قهوة مخفوقة بخيارات نكهات كراميل موكا فانيليا",
        descEn: "Blended coffee with caramel, mocha, or vanilla",
        imageUrl: `${CDN}/62/ba6d1353-3049-41cc-a8dd-4e1ccc457f84.jpeg`,
        price: 23,
      },
      {
        name: "آيس بستاشيو لاتيه",
        nameEn: "Iced Pistachio Latte",
        desc: "صوص الفستق والحليب مع الإسبريسو",
        descEn: "Pistachio sauce and milk with espresso",
        imageUrl: `${CDN}/60/718eb9a1-e8c0-45da-87f8-6524eb877bc7.jpeg`,
        price: 25,
      },
      {
        name: "آيس إسبريسو كولادا",
        nameEn: "Iced Espresso Colada",
        imageUrl: `${CDN}/66/3dff0796-19ba-429b-a5b7-abe6f1970302.jpeg`,
        price: 23,
      },
      {
        name: "آيس أوريو موكا",
        nameEn: "Iced Oreo Mocha",
        desc: "قطع الأوريو المخلوطة مع الحليب وصوص الشوكولاتة الداكنة",
        descEn: "Blended Oreo pieces with milk and dark chocolate sauce",
        imageUrl: `${CDN}/18/c1a38922-a003-44da-ad56-0416c0ef5238.jpeg`,
        price: 23,
      },
    ],
  },
  {
    id: "mojito",
    label: "موهيتو",
    labelEn: "Mojito",
    items: [
      {
        name: "موهيتو بلو بيري",
        nameEn: "Blueberry Mojito",
        desc: "مشروب غازي بنكهة التوت الأزرق",
        descEn: "Sparkling drink with blueberry flavor",
        imageUrl: `${CDN}/6/57329cdf-46c2-4164-b60c-5f8ccc2f96e6.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو روز بيري",
        nameEn: "Rose Berry Mojito",
        desc: "مشروب غازي مع التوت الأحمر",
        descEn: "Sparkling drink with red berry",
        imageUrl: `${CDN}/7/57329cdf-46c2-4164-b60c-5f8ccc2f96e6.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو حبحب",
        nameEn: "Watermelon Mojito",
        desc: "مشروب غازي مع الحبحب",
        descEn: "Sparkling drink with watermelon",
        imageUrl: `${CDN}/47/f4b55510-8faa-420e-8b22-fcf098de5388.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو فراولة",
        nameEn: "Strawberry Mojito",
        desc: "مشروب غازي مع فراولة",
        descEn: "Sparkling drink with strawberry",
        imageUrl: `${CDN}/8/fe673a31-1e38-4208-b480-b2d09dcda0f0.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو ليمون نعناع",
        nameEn: "Lemon Mint Mojito",
        desc: "مشروب غازي مع ليمون ونعناع",
        descEn: "Sparkling drink with lemon and mint",
        imageUrl: `${CDN}/9/45874118-edb0-4952-8def-20ad7d1a43dd.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو كيوي",
        nameEn: "Kiwi Mojito",
        desc: "مشروب غازي مع كيوي",
        descEn: "Sparkling drink with kiwi",
        imageUrl: `${CDN}/52/c44f3ac0-75be-42f3-b18a-655db96dbaa4.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو ليمون جنجر",
        nameEn: "Lemon Ginger Mojito",
        desc: "مشروب غازي مع ليمون وجنجر",
        descEn: "Sparkling drink with lemon and ginger",
        imageUrl: `${CDN}/50/c44f3ac0-75be-42f3-b18a-655db96dbaa4.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو برتقال",
        nameEn: "Orange Mojito",
        desc: "مشروب غازي مع برتقال",
        descEn: "Sparkling drink with orange",
        imageUrl: `${CDN}/49/c91ffae8-e187-4e4c-be73-27fbc1047eed.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو فراولة برتقال",
        nameEn: "Strawberry Orange Mojito",
        desc: "مشروب غازي مع برتقال وفراولة",
        descEn: "Sparkling drink with orange and strawberry",
        imageUrl: `${CDN}/53/04d8293e-9dd5-4e91-855b-98c83c03c239.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو باشن فروت",
        nameEn: "Passion Fruit Mojito",
        desc: "مشروب غازي مع باشن فروت",
        descEn: "Sparkling drink with passion fruit",
        imageUrl: `${CDN}/56/media-library8rpzeW`,
        price: 25,
      },
      {
        name: "موهيتو كلاسيك",
        nameEn: "Classic Mojito",
        desc: "مشروب غازي مميز",
        descEn: "Signature sparkling drink",
        imageUrl: `${CDN}/10/50ae5187-57a0-4ba5-bf4e-7462f4fa5f6c.jpeg`,
        price: 25,
      },
      {
        name: "موهيتو سفن آب",
        nameEn: "7 Up Mojito",
        desc: "سفن آب مع نكهة",
        descEn: "7 Up with flavor",
        imageUrl: `${CDN}/11/50ae5187-57a0-4ba5-bf4e-7462f4fa5f6c.jpeg`,
        price: 25,
      },
    ],
  },
  {
    id: "milkshake",
    label: "ميلك شيك",
    labelEn: "Milkshake",
    items: [
      {
        name: "ميلك شيك فراولة",
        nameEn: "Strawberry Milkshake",
        desc: "آيس كريم مخلوط مع حبات الفراولة",
        descEn: "Ice cream blended with strawberries",
        imageUrl: `${CDN}/1/11216c00-d39c-4cd9-ab83-6e589e535677.jpeg`,
        price: 25,
      },
      {
        name: "ميلك شيك فانيليا",
        nameEn: "Vanilla Milkshake",
        desc: "آيس كريم الحليب بنكهة الفانيليا",
        descEn: "Milk ice cream with vanilla flavor",
        imageUrl: `${CDN}/2/60a235aa-def0-4f2b-8a69-7322622c869f.jpeg`,
        price: 25,
      },
      {
        name: "ميلك شيك شوكليت",
        nameEn: "Chocolate Milkshake",
        desc: "آيس كريم بنكهة الشوكولاته",
        descEn: "Chocolate flavored ice cream",
        imageUrl: `${CDN}/3/4894cc92-b62b-4fff-a40c-0bdc176011c9.jpeg`,
        price: 25,
      },
      {
        name: "ميلك شيك بينك",
        nameEn: "Pink Milkshake",
        desc: "آيس كريم مخلوط مع نكهات",
        descEn: "Ice cream blended with mixed flavors",
        imageUrl: `${CDN}/4/60a235aa-def0-4f2b-8a69-7322622c869f.jpeg`,
        price: 25,
      },
      {
        name: "ميلك شيك أوريو",
        nameEn: "Oreo Milkshake",
        desc: "آيس كريم بخلطة الأوريو",
        descEn: "Ice cream blended with Oreo",
        imageUrl: `${CDN}/5/c1a38922-a003-44da-ad56-0416c0ef5238.jpeg`,
        price: 25,
      },
    ],
  },
];
